SHELL=/bin/zsh

# Go binary path
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$(go env GOPATH)/bin
# GOPATH
export GOPATH=$(go env GOPATH)

# Tiny Care Terminal
# List of accounts to read the last tweet from, comma separated
# The first in the list is read by the party parrot.
export TTC_BOTS='tinycarebot,selfcare_bot,magicrealismbot'

# Use this to have a different animal say a message in the big box.
export TTC_SAY_BOX='cat'

# List of folders to look into for `git` commits, comma separated.
export TTC_REPOS='~/projects,~/georgiatech'

# The max directory-depth to look for git repositories in
# the directories defined with `TTC_REPOS`. Note that the deeper
# the directory depth, the slower the results will be fetched.
export TTC_REPOS_DEPTH=3

# Which method is to be used to read the git commits ('gitstandup' | 'gitlog').
# If you're having problems seeing your commits in the dahsboard, set
# this value to gitlog.
export TTC_GITBOT='gitlog'

# Location/zip code to check the weather for. Both 90210 and "San Francisco, CA"
# _should_ be ok (the zip code doesn't always work -- use a location
# first, if you can). It's using weather.service.msn.com behind the curtains.
export TTC_WEATHER='Atlanta, GA'

# Set to false if you're an imperial savage. <3
export TTC_CELSIUS=true

# Unset this if you _don't_ want to use Twitter keys and want to
# use web scraping instead.
export TTC_APIKEYS=true

# Refresh the dashboard every 20 minutes.
export TTC_UPDATE_INTERVAL=10

# Turn off terminal title
export TTC_TERMINAL_TITLE=false

# Twitter api keys
export TTC_CONSUMER_KEY='Z0zvb9BUUOS1u165kWzC4C8hb'
export TTC_CONSUMER_SECRET='7LtOOBhOMxxJuLeBSses0cgMgx1Lv4Gk9eCooPr1OOsl3iixmS'
export TTC_ACCESS_TOKEN='36428666-E5EgK1Mk4JY0PU8tyyoopUlp4XUG9VMMZLgT8SoPQ'
export TTC_ACCESS_TOKEN_SECRET='Ev1t4OpQkjjLxJkZWpLPlqlAjIVhMQ3SSq615JKLDrwMm'


# Autojump sourcing
source /usr/share/autojump/autojump.zsh
